#version 450

// Tessellation Evaluation Shader

// Executes once for each vertex that is generated by the tessellation process. This stage is responsible for the final shape of the blade.
// The bending of the blade is computed using spline interpolation of the quadratic bezier curve, acting as the grass blade's spine.

//void calculateBladeTangent(in vec3 p0, in vec3 p1, in vec3 p2, out tangent) 
//{
    //vec3 a = p0 +
//}

void main() 
{    

}